AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless GitHub app

Parameters:
  githubAppId:
    Description: The App ID of your GitHub app
    Type: String
  githubWebhookSecret:
    Description: The webhook secret of your GitHub app
    Type: String
  githubPrivateKey:
    Description: The base64 encoded private key of your GitHub app
    Type: String
  githubUser:
    Description: The user with admin access
    Type: String
  githubPat:
    Description: The PAT of the user with admin access
    Type: String
  emergencyLabel:
    Description: The label to use for emergency issues
    Type: String
  issueTitle:
    Description: The title of the issue
    Default: Emergency PR Audit
    Type: String
  issueBodyFile:
    Description: The file containing the body of the issue
    Default: issueBody.md
    Type: String
  issueAssignees:
    Description: The assignees of the issue in a comma separated list
    Type: String
  approvePr:
    Description: Enable the app to approve PRs
    Default: true
    AllowedValues:
      - true
      - false
    Type: String
  createIssue:
    Description: Enable the app to create issues
    Default: true
    AllowedValues:
      - true
      - false
    Type: String
  mergePr:
    Description: Enable the app to merge PRs
    Default: true
    AllowedValues:
      - true
      - false
    Type: String

Resources:
  webhooks:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-webhooks
      Description: Basic Auth Funtion
      CodeUri: .
      Handler: handler.webhooks
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 20
      Events:
        ApiEvent:
          Type: HttpApi
      Environment:
        Variables:
          APP_ID: !Ref githubAppId
          WEBHOOK_SECRET: !Ref githubWebhookSecret
          PRIVATE_KEY: !Ref githubPrivateKey
          GITHUB_USER: !Ref githubUser
          GITHUB_PAT: !Ref githubPat
          EMERGENCY_LABEL: !Ref emergencyLabel
          ISSUE_TITLE: !Ref issueTitle
          ISSUE_BODY_FILE: !Ref issueBodyFile
          ISSUE_ASSIGNEES: !Ref issueAssignees
          APPROVE_PR: !Ref approvePr
          CREATE_ISSUE: !Ref createIssue
          MERGE_PR: !Ref mergePr
